import { DURATION_5D_AAPL } from "./DURATION_5D_AAPL";
import { DURATION_MTD_AAPL } from "./DURATION_MTD_AAPL";
import { DURATION_MTD_IBM } from "./DURATION_MTD_IBM";

import { DURATION_MTD_GOOG } from "./DURATION_MTD_GOOG";

import { DURATION_L3Y_AAPL } from "./DURATION_L3Y_AAPL";
import { DURATION_L5Y_AAPL } from "./DURATION_L5Y_AAPL";
import { DURATION_L20Y_AAPL } from "./DURATION_L20Y_AAPL";
export {
  DURATION_5D_AAPL,
  DURATION_MTD_AAPL,
  DURATION_MTD_GOOG,
  DURATION_MTD_IBM,
  DURATION_L3Y_AAPL,
  DURATION_L5Y_AAPL,
  DURATION_L20Y_AAPL,
};
