import { SEARCH_QUERY_GOOG } from "./SEARCH_QUERY_GOOG";
import { SEARCH_QUERY_IBM } from "./SEARCH_QUERY_IBM";
import { SEARCH_QUERY_AAPL } from "./SEARCH_QUERY_AAPL";

export { SEARCH_QUERY_AAPL, SEARCH_QUERY_IBM, SEARCH_QUERY_GOOG };
